media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: src/projects
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: technologies, label: Technologies, type: string }
      - { name: id, label: ID, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: og, label: OG Image, type: image }
      - { name: body, label: Body, type: rich-text }