media:
  input: public
  output: ""
content:
  - name: posts
    label: Posts
    type: collection
    path: src/projects
    view:
      fields: [ title, date ]
      sort: [date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: technologies, label: Technologies, type: string }
      - { name: id, label: ID, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: og, label: OG Image, type: string }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }